modLoader = "javafml"
loaderVersion = "[${loaderVersion},)"
license = "LGPL-3.0"

[[mods]]
modId = "moremcmeta_properties_reader_plugin"
version = "${modVersion}"
displayName = "MoreMcmeta Properties Reader Plugin"
authors = "soir20"
description = '''
Default plugin for MoreMcmeta that reads OptiFine (.properties) metadata files.
'''
#logoFile = ""

[[dependencies.moremcmeta_properties_reader_plugin]]
modId = "moremcmeta"
mandatory = true
versionRange = "[${minMoreMcmetaVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.moremcmeta_properties_reader_plugin]]
modId = "forge"
mandatory = true
versionRange = "[${loaderVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moremcmeta_properties_reader_plugin]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"